version: '3.8'

services:
  # Frontend Service
  frontend:
    build: ./frontend/estore
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    volumes:
      - ./frontend/estore:/app  # Syncs frontend code changes
      - /app/node_modules  # Preserves container's node_modules
    env_file:
      - ./frontend/estore/test.env
    command: npm run dev  # Ensure this starts a development server

  # Backend Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@estorecluster.jrm39.mongodb.net/?retryWrites=true&w=majority&appName=estoreCluster
      - JWT_KEY=${JWT_KEY}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - FRONTEND_URL=${FRONTEND_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./backend:/app  # Syncs backend code changes
    depends_on:
      - mongo
    env_file:
      - ./backend/test.env
    command: npm run dev  # Ensure this uses nodemon or a development server

  # MongoDB Service
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: